`dotnetup` should not use existing user install locations over the `default`
@333fred was trying out `dotnetup` and mentioned that he hit this error:

```
➜ dotnetup
Error: The install path '/home/FOO/.local/share/dnvm/dn' already contains a .NET installation that is not tracked by
dotnetup. To avoid conflicts, use a different install path, remove the existing installation first, or use the --untracked
option to install without tracking.
```

He had to remove `/home/FOO/.local/share/dnvm` from the path and it was confusing behavior in his perspective that we starting trying to use the `dnvm` path to install to.

I think the behavior is well intended but perhaps we should change it to not do this. Most of the time the user existing location will have untracked installs in it, which we might change and make this work, but I don't think this is what users will expect.

I'm open to opinions and no problem if we just toss this PR and decide to keep the behavior as-is.