A bunch of msbuild sdks depended on an old STJ and so were broken when run in the new VS.
    Exception: "System.MissingMethodException: Method not found: 'Void System.Text.Json.Utf8JsonReader..ctor(System.ReadOnlySpan`1<Byte>, Boolean, System.Text.Json.JsonReaderState)'.