Put `lock` inside ComponentManager to make it thread-safe
Problem appeared on CI with following exception:
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary2.set_Item(TKey key, TValue value)
   at Microsoft.TemplateEngine.Edge.Settings.ComponentManager.AddComponent(Type type, IIdentifiedComponent component) in //src/Microsoft.TemplateEngine.Edge/Settings/ComponentManager.cs:line 263
   at Microsoft.TemplateEngine.Edge.Settings.ComponentManager.TryGetComponent[T](Guid id, T& component) in //src/Microsoft.TemplateEngine.Edge/Settings/ComponentManager.cs:line 173
   at Microsoft.TemplateEngine.Edge.Settings.ComponentManager.OfTypeT+MoveNext() in //src/Microsoft.TemplateEngine.Edge/Settings/ComponentManager.cs:line 122
   at Microsoft.TemplateEngine.Edge.Settings.Scanner.ScanMountPointForTemplatesAndLangpacks(MountPointScanSource source, ScanResult scanResult) in //src/Microsoft.TemplateEngine.Edge/Settings/Scanner.cs:line 165
   at Microsoft.TemplateEngine.Edge.Settings.Scanner.Scan(String sourceLocation) in //src/Microsoft.TemplateEngine.Edge/Settings/Scanner.cs:line 38
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.<>c__DisplayClass30_0.<RebuildCacheFromSettingsIfNotCurrent>b__0(ITemplatePackage package) in //src/Microsoft.TemplateEngine.Edge/Settings/SettingsLoader.cs:line 404
```
Will probably make better solution when fixing dotnet/templating#3075

Commit migrated from https://github.com/dotnet/templating/commit/7e14ef44c849e230176477bf271ceab3db74ea7e